URI_BASE = "/aifse/ipmmc/v1/"
HELLO_TEAM = "Hello Team!"
SUCCESS_MESSAGE = "Success"
ERROR_MESSAGE = "Error"
SUCCESS_CODE = "S000"
ERROR_CODE = "E000"
DUPLICATE_PART = "Duplicate Part: Part already exists"
UPLOAD_SUCCESSFUL = "Part uploaded successfully"